apiVersion: v1
kind: Service
metadata:
  name: app002
  namespace: demo
  labels:
    app: app002
    cis.f5.com/as3-tenant: app002
    cis.f5.com/as3-app: app002
    cis.f5.com/as3-pool: pool_002
spec:
  ports:
  - name: app002
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app002
