apiVersion: v1
kind: Service
metadata:
  name: app008
  namespace: demo
  labels:
    app: app008
    cis.f5.com/as3-tenant: app008
    cis.f5.com/as3-app: app008
    cis.f5.com/as3-pool: pool_008
spec:
  ports:
  - name: app008
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: app008
