kind: ConfigMap
apiVersion: v1
metadata:
  name: app005
  namespace: demo
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "app005",
            "label": "https",
            "remark": "app005 Template",
            "app005": {
                "class": "Tenant",
                "app005": {
                    "class": "Application",
                    "template": "generic",
                    "app005": {
                        "class": "Service_HTTP",
                        "remark": "app005",
                        "virtualAddresses": [
                            "192.168.179.5"
                        ],
                        "virtualPort": 80,
                        "pool": "pool_005"
                    },
                    "pool_005": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": [],
                                "connectionLimit": 10
                            }
                        ]
                    }
                }
            }
        }
    }
