apiVersion: v1
kind: Service
metadata:
  name: app005
  namespace: demo
  labels:
    app: app005
    cis.f5.com/as3-tenant: app005
    cis.f5.com/as3-app: app005
    cis.f5.com/as3-pool: pool_005
spec:
  ports:
  - name: app005
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app005
