kind: ConfigMap
apiVersion: v1
metadata:
  name: garden-vs
  namespace: garden
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
          "class": "ADC",
          "schemaVersion": "3.18.0",
          "label": "http",
          "garden_vs": {
              "class": "Tenant",
              "garden_entry": {
                  "class": "Application",
                  "template": "generic",
                  "garden": {
                      "class": "Service_HTTP",
                      "persistenceMethods": [ "cookie" ],
                      "virtualAddresses": [ "10.1.10.109" ],
                      "iRules": ["url_switch"]
                  },
                  "url_switch": {
                      "class": "iRule",
                      "iRule": "when HTTP_REQUEST { \n set dpool [class match -value [HTTP::host] equals gardenpool] \n if { [info exists dpool ]} {  pool $dpool } }"
                  },
                  "gardenpool": {
                      "class": "Data_Group",
                      "storageType": "internal",
                      "name": "internalHostnames",
                      "keyDataType": "string",
                      "records": [
                         {"key": "www.rose.com", "value": "/garden_c1/rose/rose"},
                         {"key": "www.tulip.com", "value": "/garden_c2/tulip/tulip"}
                      ]
                  }
               }
            }
        }
    }