apiVersion: v1
kind: Service
metadata:
  name: app011
  namespace: demo
  labels:
    app: app011
    cis.f5.com/as3-tenant: app011
    cis.f5.com/as3-app: app011
    cis.f5.com/as3-pool: pool_011
spec:
  ports:
  - name: app011
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app011
