apiVersion: v1
kind: Service
metadata:
  name: app004
  namespace: demo
  labels:
    app: app004
    cis.f5.com/as3-tenant: app004
    cis.f5.com/as3-app: app004
    cis.f5.com/as3-pool: pool_004
spec:
  ports:
  - name: app004
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app004
