kind: ConfigMap
apiVersion: v1
metadata:
  name: app102
  namespace: demo
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
          "class": "ADC",
          "schemaVersion": "3.18.0",
          "label": "http",
          "id": "app102",
          "app102-apple-C2": {
              "class": "Tenant",
              "app102-apple": {
                  "class": "Application",
                  "template": "generic",
                  "app102-apple": {
                      "class": "Pool",
                      "monitors": [ "http" ],                      
                      "loadBalancingMode": "least-connections-member",
                      "members": [
                          {
                              "servicePort": 8080,
                              "serverAddresses": []
                          }
                      ] 
                  }
               }
            }
        }
    }
