kind: ConfigMap
apiVersion: v1
metadata:
  name: app102
  namespace: demo
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
          "class": "ADC",
          "schemaVersion": "3.18.0",
          "label": "http",
          "id": "app102",
          "app102": {
              "class": "Tenant",
              "app102-apple": {
                  "class": "Application",
                  "template": "generic",
                  "app102-apple_vs": {
                      "class": "Service_HTTP",
                      "virtualAddresses": [ "192.168.179.102" ],
                      "persistenceMethods": [],
                      "iRules": ["url_switch_mc_ratio"]
                  },
                  "app102-apple": {
                      "class": "Pool",
                      "monitors": [ "http" ],                      
                      "loadBalancingMode": "least-connections-member",
                      "members": [
                          {
                              "servicePort": 8080,
                              "serverAddresses": []
                          }
                      ]
                  },
                  "url_switch_mc_ratio": {
                      "class": "iRule",
                      "iRule": "when HTTP_REQUEST { \n if { [HTTP::header "Host"] starts_with "apple" }  { \n pool /app102/app102-apple/app102-apple \n } else { \n pool /app102-apple-C2/app102-apple/app102-apple \n } \n }" 
                  }
               }
            }
        }
    }
