apiVersion: v1
kind: Service
metadata:
  name: app012
  namespace: demo
  labels:
    app: app012
    cis.f5.com/as3-tenant: app012
    cis.f5.com/as3-app: app012
    cis.f5.com/as3-pool: pool_012
spec:
  ports:
  - name: app012
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app012
