apiVersion: apps/v1
kind: Deployment
metadata:
  name: rose
  namespace: garden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rose
  template:
    metadata:
      labels:
        app: rose
    spec:
      containers:
      - name: rose
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rose-svc
  namespace: garden
  labels:
    cis.f5.com/as3-tenant: garden_c2
    cis.f5.com/as3-app: garden
    cis.f5.com/as3-pool: rose
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: rose
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulip
  namespace: garden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tulip
  template:
    metadata:
      labels:
        app: tulip
    spec:
      containers:
      - name: tulip
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tulip-svc
  namespace: garden
  labels:
    cis.f5.com/as3-tenant: garden_c2
    cis.f5.com/as3-app: garden
    cis.f5.com/as3-pool: tulip
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tulip