kind: ConfigMap
apiVersion: v1
metadata:
  name: garden-pool
  namespace: garden
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
          "class": "ADC",
          "schemaVersion": "3.18.0",
          "label": "http",
          "garden_c2": {
              "class": "Tenant",
              "garden": {
                  "class": "Application",
                  "template": "generic",
                  "tulip": {
                      "class": "Pool",
                      "monitors": [ "http" ],
                      "loadBalancingMode": "least-connections-member",
                      "members": [
                          {
                              "servicePort": 80,
                              "serverAddresses": []
                          }
                      ]
                  },
                  "rose": {
                      "class": "Pool",
                      "monitors": [ "http" ],
                      "loadBalancingMode": "least-connections-member",
                      "members": [
                          {
                              "servicePort": 80,
                              "serverAddresses": []
                          }
                      ]
                  }
               }
          }
       }
    }