kind: ConfigMap
apiVersion: v1
metadata:
  name: app007
  namespace: demo
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "app007",
            "label": "http",
            "remark": "app007 Template",
            "app007": {
                "class": "Tenant",
                "app007": {
                    "class": "Application",
                    "template": "generic",
                    "app007": {
                        "class": "Service_HTTP",
                        "remark": "app007",
                        "virtualAddresses": [
                            "192.168.179.7"
                        ],
                        "profileHTTP": { "use": "http_profile_XFF" },
                        "virtualPort": 80,
                        "pool": "pool_007"
                    },
                    "pool_007": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "http_profile_XFF": {
                     "class": "HTTP_Profile",
                     "xForwardedFor": true
                  }
                }
            }
        }
    }
