apiVersion: v1
kind: Service
metadata:
  name: app007
  namespace: demo
  labels:
    app: app007
    cis.f5.com/as3-tenant: app007
    cis.f5.com/as3-app: app007
    cis.f5.com/as3-pool: pool_007
spec:
  ports:
  - name: app007
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app007
