kind: ConfigMap
apiVersion: v1
metadata:
  name: app006
  namespace: cistest
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "app006",
            "label": "http",
            "remark": "app006 Template",
            "app006": {
                "class": "Tenant",
                "app006": {
                    "class": "Application",
                    "template": "generic",
                    "app006": {
                        "class": "Service_HTTP",
                        "remark": "app006",
                        "virtualAddresses": [
                            "192.168.179.6"
                        ],
                        "persistenceMethods": ["source-address"],
                        "virtualPort": 80
                    },
                    "pool_006": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
