apiVersion: v1
kind: Service
metadata:
  name: app014
  namespace: demo
  labels:
    app: app014
    cis.f5.com/as3-tenant: app014
    cis.f5.com/as3-app: app014
    cis.f5.com/as3-pool: pool_014
spec:
  ports:
  - name: app014
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app014
