apiVersion: apps/v1
kind: Deployment
metadata:
  name: app010
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app010
  template:
    metadata:
      labels:
        app: app010
    spec:
      containers:
      - image: nginxdemos/nginx-hello:plain-text
        imagePullPolicy: IfNotPresent
        name: app010
        ports:
        - containerPort: 8080
          protocol: TCP

