apiVersion: v1
kind: Service
metadata:
  name: app010
  namespace: demo
  labels:
    app: app010
    cis.f5.com/as3-tenant: app010
    cis.f5.com/as3-app: app010
    cis.f5.com/as3-pool: pool_010
spec:
  ports:
  - name: app010
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app010
